site_name: Dungeon Adventure Developer Documentation
theme:
  name: material
  features:
    - content.code.annotate
  palette:
    primary: indigo
    accent: amber
nav:
  - Home: index.md
  - Project Overview: project-overview.md
  - Core Components:
      - Dungeon: core-components/dungeon.md
      - Characters: core-components/characters.md
      - Items: core-components/items.md
  - Game Flow: game-flow.md
  - Controllers:
      - Game Controller: controllers/game-controller.md
      - Player Action Controller: controllers/player-action-controller.md
  - Views:
      - Console View: views/console-view.md
      - Map Visualizer: views/map-visualizer.md
  - Enums and Constants: enums-and-constants.md
  - Utility Classes: utility-classes.md
  - Testing: testing.md
  - Development Guide: development-guide.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search
  - typeset
